# Generated by Django 3.2.4 on 2021-08-12 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_coin_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
