# Generated by Django 3.2.4 on 2021-08-12 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(max_length=20)),
                ('usdValue', models.FloatField(max_length=20)),
                ('coindId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dashboard.coin')),
            ],
        ),
    ]
