# Generated by Django 3.2.6 on 2021-08-21 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0005_rename_coindid_portfolio_coinid'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
